/* Strategy provided by p6-XML-LibXML:author<FROGGS> */
#ifdef _WIN32
#define DLLEXPORT __declspec(dllexport)
#else
#define DLLEXPORT extern
#endif

#include <webkit2/webkit2.h>
//#include <webkit2/webkit-web-extension.h>
//#include <jsc/jsc.h>
// #include <JavaScriptCore/JavaScript.h>

#define s(name)     DLLEXPORT int sizeof_ ## name () { return sizeof(name); }

s(JSCContext)
s(JSCContextClass)
s(JSCException)
s(JSCExceptionClass)
s(JSCValue)
s(JSCValueClass)
s(JSCVirtualMachine)
s(JSCVirtualMachineClass)
s(JSCWeakValue)
s(JSCWeakValueClass)
s(WebKitAuthenticationRequest)
s(WebKitAuthenticationRequestClass)
s(WebKitAutomationSession)
s(WebKitAutomationSessionClass)
s(WebKitBackForwardList)
s(WebKitBackForwardListClass)
s(WebKitBackForwardListItem)
s(WebKitBackForwardListItemClass)
s(WebKitColorChooserRequest)
s(WebKitColorChooserRequestClass)
s(WebKitContextMenu)
s(WebKitContextMenuClass)
s(WebKitContextMenuItem)
s(WebKitContextMenuItemClass)
s(WebKitCookieManager)
s(WebKitCookieManagerClass)
s(WebKitDeviceInfoPermissionRequest)
s(WebKitDeviceInfoPermissionRequestClass)
// s(WebKitDOMAttr)
// s(WebKitDOMAttrClass)
// s(WebKitDOMBlob)
// s(WebKitDOMBlobClass)
// s(WebKitDOMCDATASection)
// s(WebKitDOMCDATASectionClass)
// s(WebKitDOMCharacterData)
// s(WebKitDOMCharacterDataClass)
// s(WebKitDOMClientRect)
// s(WebKitDOMClientRectClass)
// s(WebKitDOMClientRectList)
// s(WebKitDOMClientRectListClass)
// s(WebKitDOMComment)
// s(WebKitDOMCommentClass)
// s(WebKitDOMCSSRule)
// s(WebKitDOMCSSRuleClass)
// s(WebKitDOMCSSRuleList)
// s(WebKitDOMCSSRuleListClass)
// s(WebKitDOMCSSStyleDeclaration)
// s(WebKitDOMCSSStyleDeclarationClass)
// s(WebKitDOMCSSStyleSheet)
// s(WebKitDOMCSSStyleSheetClass)
// s(WebKitDOMCSSValue)
// s(WebKitDOMCSSValueClass)
// s(WebKitDOMDocument)
// s(WebKitDOMDocumentClass)
// s(WebKitDOMDocumentFragment)
// s(WebKitDOMDocumentFragmentClass)
// s(WebKitDOMDocumentType)
// s(WebKitDOMDocumentTypeClass)
// s(WebKitDOMDOMImplementation)
// s(WebKitDOMDOMImplementationClass)
// s(WebKitDOMDOMSelection)
// s(WebKitDOMDOMSelectionClass)
// s(WebKitDOMDOMTokenList)
// s(WebKitDOMDOMTokenListClass)
// s(WebKitDOMDOMWindow)
// s(WebKitDOMDOMWindowClass)
// s(WebKitDOMElement)
// s(WebKitDOMElementClass)
// s(WebKitDOMEntityReference)
// s(WebKitDOMEntityReferenceClass)
// s(WebKitDOMEvent)
// s(WebKitDOMEventClass)
// s(WebKitDOMEventTargetIface)
// s(WebKitDOMFile)
// s(WebKitDOMFileClass)
// s(WebKitDOMFileList)
// s(WebKitDOMFileListClass)
// s(WebKitDOMHTMLAnchorElement)
// s(WebKitDOMHTMLAnchorElementClass)
// s(WebKitDOMHTMLAppletElement)
// s(WebKitDOMHTMLAppletElementClass)
// s(WebKitDOMHTMLAreaElement)
// s(WebKitDOMHTMLAreaElementClass)
// s(WebKitDOMHTMLBaseElement)
// s(WebKitDOMHTMLBaseElementClass)
// s(WebKitDOMHTMLBaseFontElement)
// s(WebKitDOMHTMLBaseFontElementClass)
// s(WebKitDOMHTMLBodyElement)
// s(WebKitDOMHTMLBodyElementClass)
// s(WebKitDOMHTMLBRElement)
// s(WebKitDOMHTMLBRElementClass)
// s(WebKitDOMHTMLButtonElement)
// s(WebKitDOMHTMLButtonElementClass)
// s(WebKitDOMHTMLCanvasElement)
// s(WebKitDOMHTMLCanvasElementClass)
// s(WebKitDOMHTMLCollection)
// s(WebKitDOMHTMLCollectionClass)
// s(WebKitDOMHTMLDirectoryElement)
// s(WebKitDOMHTMLDirectoryElementClass)
// s(WebKitDOMHTMLDivElement)
// s(WebKitDOMHTMLDivElementClass)
// s(WebKitDOMHTMLDListElement)
// s(WebKitDOMHTMLDListElementClass)
// s(WebKitDOMHTMLDocument)
// s(WebKitDOMHTMLDocumentClass)
// s(WebKitDOMHTMLElement)
// s(WebKitDOMHTMLElementClass)
// s(WebKitDOMHTMLEmbedElement)
// s(WebKitDOMHTMLEmbedElementClass)
// s(WebKitDOMHTMLFieldSetElement)
// s(WebKitDOMHTMLFieldSetElementClass)
// s(WebKitDOMHTMLFontElement)
// s(WebKitDOMHTMLFontElementClass)
// s(WebKitDOMHTMLFormElement)
// s(WebKitDOMHTMLFormElementClass)
// s(WebKitDOMHTMLFrameElement)
// s(WebKitDOMHTMLFrameElementClass)
// s(WebKitDOMHTMLFrameSetElement)
// s(WebKitDOMHTMLFrameSetElementClass)
// s(WebKitDOMHTMLHeadElement)
// s(WebKitDOMHTMLHeadElementClass)
// s(WebKitDOMHTMLHeadingElement)
// s(WebKitDOMHTMLHeadingElementClass)
// s(WebKitDOMHTMLHRElement)
// s(WebKitDOMHTMLHRElementClass)
// s(WebKitDOMHTMLHtmlElement)
// s(WebKitDOMHTMLHtmlElementClass)
// s(WebKitDOMHTMLIFrameElement)
// s(WebKitDOMHTMLIFrameElementClass)
// s(WebKitDOMHTMLImageElement)
// s(WebKitDOMHTMLImageElementClass)
// s(WebKitDOMHTMLInputElement)
// s(WebKitDOMHTMLInputElementClass)
// s(WebKitDOMHTMLLabelElement)
// s(WebKitDOMHTMLLabelElementClass)
// s(WebKitDOMHTMLLegendElement)
// s(WebKitDOMHTMLLegendElementClass)
// s(WebKitDOMHTMLLIElement)
// s(WebKitDOMHTMLLIElementClass)
// s(WebKitDOMHTMLLinkElement)
// s(WebKitDOMHTMLLinkElementClass)
// s(WebKitDOMHTMLMapElement)
// s(WebKitDOMHTMLMapElementClass)
// s(WebKitDOMHTMLMarqueeElement)
// s(WebKitDOMHTMLMarqueeElementClass)
// s(WebKitDOMHTMLMenuElement)
// s(WebKitDOMHTMLMenuElementClass)
// s(WebKitDOMHTMLMetaElement)
// s(WebKitDOMHTMLMetaElementClass)
// s(WebKitDOMHTMLModElement)
// s(WebKitDOMHTMLModElementClass)
// s(WebKitDOMHTMLObjectElement)
// s(WebKitDOMHTMLObjectElementClass)
// s(WebKitDOMHTMLOListElement)
// s(WebKitDOMHTMLOListElementClass)
// s(WebKitDOMHTMLOptGroupElement)
// s(WebKitDOMHTMLOptGroupElementClass)
// s(WebKitDOMHTMLOptionElement)
// s(WebKitDOMHTMLOptionElementClass)
// s(WebKitDOMHTMLOptionsCollection)
// s(WebKitDOMHTMLOptionsCollectionClass)
// s(WebKitDOMHTMLParagraphElement)
// s(WebKitDOMHTMLParagraphElementClass)
// s(WebKitDOMHTMLParamElement)
// s(WebKitDOMHTMLParamElementClass)
// s(WebKitDOMHTMLPreElement)
// s(WebKitDOMHTMLPreElementClass)
// s(WebKitDOMHTMLQuoteElement)
// s(WebKitDOMHTMLQuoteElementClass)
// s(WebKitDOMHTMLScriptElement)
// s(WebKitDOMHTMLScriptElementClass)
// s(WebKitDOMHTMLSelectElement)
// s(WebKitDOMHTMLSelectElementClass)
// s(WebKitDOMHTMLStyleElement)
// s(WebKitDOMHTMLStyleElementClass)
// s(WebKitDOMHTMLTableCaptionElement)
// s(WebKitDOMHTMLTableCaptionElementClass)
// s(WebKitDOMHTMLTableCellElement)
// s(WebKitDOMHTMLTableCellElementClass)
// s(WebKitDOMHTMLTableColElement)
// s(WebKitDOMHTMLTableColElementClass)
// s(WebKitDOMHTMLTableElement)
// s(WebKitDOMHTMLTableElementClass)
// s(WebKitDOMHTMLTableRowElement)
// s(WebKitDOMHTMLTableRowElementClass)
// s(WebKitDOMHTMLTableSectionElement)
// s(WebKitDOMHTMLTableSectionElementClass)
// s(WebKitDOMHTMLTextAreaElement)
// s(WebKitDOMHTMLTextAreaElementClass)
// s(WebKitDOMHTMLTitleElement)
// s(WebKitDOMHTMLTitleElementClass)
// s(WebKitDOMHTMLUListElement)
// s(WebKitDOMHTMLUListElementClass)
// s(WebKitDOMKeyboardEvent)
// s(WebKitDOMKeyboardEventClass)
// s(WebKitDOMMediaList)
// s(WebKitDOMMediaListClass)
// s(WebKitDOMMouseEvent)
// s(WebKitDOMMouseEventClass)
// s(WebKitDOMNamedNodeMap)
// s(WebKitDOMNamedNodeMapClass)
// s(WebKitDOMNode)
// s(WebKitDOMNodeClass)
// s(WebKitDOMNodeFilterIface)
// s(WebKitDOMNodeIterator)
// s(WebKitDOMNodeIteratorClass)
// s(WebKitDOMNodeList)
// s(WebKitDOMNodeListClass)
// s(WebKitDOMObject)
// s(WebKitDOMObjectClass)
// s(WebKitDOMProcessingInstruction)
// s(WebKitDOMProcessingInstructionClass)
// s(WebKitDOMRange)
// s(WebKitDOMRangeClass)
// s(WebKitDOMStyleSheet)
// s(WebKitDOMStyleSheetClass)
// s(WebKitDOMStyleSheetList)
// s(WebKitDOMStyleSheetListClass)
// s(WebKitDOMText)
// s(WebKitDOMTextClass)
// s(WebKitDOMTreeWalker)
// s(WebKitDOMTreeWalkerClass)
// s(WebKitDOMUIEvent)
// s(WebKitDOMUIEventClass)
// s(WebKitDOMWheelEvent)
// s(WebKitDOMWheelEventClass)
// s(WebKitDOMXPathExpression)
// s(WebKitDOMXPathExpressionClass)
// s(WebKitDOMXPathNSResolverIface)
// s(WebKitDOMXPathResult)
// s(WebKitDOMXPathResultClass)
s(WebKitDownload)
s(WebKitDownloadClass)
s(WebKitEditorState)
s(WebKitEditorStateClass)
s(WebKitFaviconDatabase)
s(WebKitFaviconDatabaseClass)
s(WebKitFileChooserRequest)
s(WebKitFileChooserRequestClass)
s(WebKitFindController)
s(WebKitFindControllerClass)
s(WebKitFormSubmissionRequest)
s(WebKitFormSubmissionRequestClass)
s(WebKitGeolocationManager)
s(WebKitGeolocationManagerClass)
s(WebKitGeolocationPermissionRequest)
s(WebKitGeolocationPermissionRequestClass)
s(WebKitHitTestResult)
s(WebKitHitTestResultClass)
s(WebKitInputMethodContext)
s(WebKitInputMethodContextClass)
s(WebKitInstallMissingMediaPluginsPermissionRequest)
s(WebKitInstallMissingMediaPluginsPermissionRequestClass)
s(WebKitNavigationPolicyDecision)
s(WebKitNavigationPolicyDecisionClass)
s(WebKitNotification)
s(WebKitNotificationClass)
s(WebKitNotificationPermissionRequest)
s(WebKitNotificationPermissionRequestClass)
s(WebKitOptionMenu)
s(WebKitOptionMenuClass)
s(WebKitPermissionRequestIface)
s(WebKitPlugin)
s(WebKitPluginClass)
s(WebKitPointerLockPermissionRequest)
s(WebKitPointerLockPermissionRequestClass)
s(WebKitPolicyDecision)
s(WebKitPolicyDecisionClass)
s(WebKitPrintCustomWidget)
s(WebKitPrintCustomWidgetClass)
s(WebKitPrintOperation)
s(WebKitPrintOperationClass)
s(WebKitResponsePolicyDecision)
s(WebKitResponsePolicyDecisionClass)
s(WebKitSecurityManager)
s(WebKitSecurityManagerClass)
s(WebKitSettings)
s(WebKitSettingsClass)
s(WebKitURIRequest)
s(WebKitURIRequestClass)
s(WebKitURIResponse)
s(WebKitURIResponseClass)
s(WebKitURISchemeRequest)
s(WebKitURISchemeRequestClass)
s(WebKitUserContentFilterStore)
s(WebKitUserContentFilterStoreClass)
s(WebKitUserContentManager)
s(WebKitUserContentManagerClass)
s(WebKitUserMediaPermissionRequest)
s(WebKitUserMediaPermissionRequestClass)
s(WebKitUserMessage)
s(WebKitUserMessageClass)
s(WebKitWebContext)
s(WebKitWebContextClass)
s(WebKitWebInspector)
s(WebKitWebInspectorClass)
s(WebKitWebResource)
s(WebKitWebResourceClass)
s(WebKitWebsiteDataManager)
s(WebKitWebsiteDataManagerClass)
s(WebKitWebView)
s(WebKitWebViewBase)
s(WebKitWebViewBaseClass)
s(WebKitWebViewClass)
s(WebKitWindowProperties)
s(WebKitWindowPropertiesClass)
